### ISSUE TITLE
“pip install -r requirements.txt” error

### ISSUE THREAD

**Issue by Buen16** [UFund-Me/Qbot#19]
env: win10x64 python3.9
**看起来似乎是安装quantstats失败，并且我单独用pip install安装quantstats之后，再pip install -r requirements.txt也还是报如下的错**
INFO: pip is looking at multiple versions of quantstats to determine which version is compatible with other requirements. This could take a while.
  Downloading http://pypi.doubanio.com/packages/a9/af/c716bdc8eb8329698b88c2d16673ce98ad271e0456af557d9321624914a4/QuantStats-0.0.48-py2.py3-none-any.whl (40 kB)
     ---------------------------------------- 40.3/40.3 kB ? eta 0:00:00
  Downloading http://pypi.doubanio.com/packages/02/92/15207bfd641799fe73fbfc9e91222032b2a43260bac8db794aff8d32d6de/QuantStats-0.0.47.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/7a/33/08d1a0978b6a45c6d97cf806cd9ce1c1d06fa295e8229113071c180669ba/QuantStats-0.0.46.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/1f/20/460ecfbdbb5340eac591567d3aec5c004e1cdb14bb813bbf2c631e26f4be/QuantStats-0.0.45.tar.gz (35 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/97/6d/01d01da549f5cd00e0d2e724f430df7ae09293f7e7bc1da59c8d7f1e0cb5/QuantStats-0.0.44.tar.gz (35 kB)
  Preparing metadata (setup.py) ... done
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading http://pypi.doubanio.com/packages/5a/a0/29addbacdf84f44ed75a75e9076c727955be50c4cd3ea9c8f725640e3621/QuantStats-0.0.43.tar.gz (35 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/6f/ce/1f7d63ccf8dc2a6c6b159324eb23a516824a8f58764964a3ea54a5a67ad5/QuantStats-0.0.42.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/d4/af/6c313aec1857a4fe097e76960f37591fb9651d650c8bceab526b516fe1d1/QuantStats-0.0.41.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/b3/db/cfbe7729a566482c6a6b729741f45ff9fb0aa13af903d843b9a612dcf2ad/QuantStats-0.0.40.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/d2/32/69f1355f848dcc3d199cc3089fea117181cc94e101f22cfbbcd88eca12e7/QuantStats-0.0.39.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/0a/af/2a4222b4a1338cb0ea953875b073718cedd37983214232b0ccf6d4136aef/QuantStats-0.0.38.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/21/a8/aeb2c36a84f27fc8fcfd8796a2408da19fd9b7eb28af0e77ee20ffa4f076/QuantStats-0.0.37.tar.gz (33 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/73/5e/5c0902ea7dac31b3564d3dab95d6c47ab0bcdad19a456f8c10791ea34e25/QuantStats-0.0.36.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/08/98/f29adef26bfed74234ad931fa1b0bdd10780f7ecef0a3548cd6d2279581d/QuantStats-0.0.35.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/8c/3f/49bbcd3c74885c6552c92eab6ea6a8b88770fe25ada1a9b4b21dafb52ed8/QuantStats-0.0.34.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/a8/65/570ea7065e4cbe335187f0178dfbae4b7a7d81cd4052968f738c724bbce8/QuantStats-0.0.33.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/ce/04/d2116cdde4ddbc73f701cfd546c0acbcd3cd988a53d9af62c184c0b690db/QuantStats-0.0.32.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/93/a7/80d6b09c333ffa72142c511737489305c22c4abc6b86b5a9eaafa47bf38a/QuantStats-0.0.31.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/f6/cb/e712c4d3ecc65ad4829a140f3323371677118b43e55342389addf6795e4c/QuantStats-0.0.30.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
  Downloading http://pypi.doubanio.com/packages/52/44/9463879e8f6b786a2a703a0955e28cd91047a1975e09992c50d38fce15e2/QuantStats-0.0.29.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      **Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\S11\AppData\Local\Temp\pip-install-crqayik0\quantstats_10e3ffc87caf4b8e8bb172ab07370f9e\setup.py", line 30, in <module>
          with io.open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\S11\\AppData\\Local\\Temp\\pip-install-crqayik0\\quantstats_10e3ffc87caf4b8e8bb172ab07370f9e\\requirements.txt'**
      [end of output]

**Comment by zengxiaobai** [comment]
请问这个解决了吗 我也遇到一样的问题 
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\XXX\AppData\Local\Temp\pip-install-cdanpizg\quantstats_9cde7b393c2e4ef987a14ad190a17e28\setup.py", line 30, in <module>
          with io.open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\pip-install-cdanpizg\\quantstats_9cde7b393c2e4ef987a14ad190a17e28\\requirements.txt'

**Comment by gyk6985432** [comment]
我也遇到了，C盘路径下没找到那个文件

**Comment by gyk6985432** [comment]
升级pip就解决了，conda下：
`python.exe -m pip install --upgrade pip`

**Comment by XuanhengTang** [comment]
同样遇到了这个问题，请问有解决方法吗
Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/52/44/9463879e8f6b786a2a703a0955e28cd91047a1975e09992c50d38fce15e2/QuantStats-0.0.29.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-l_ropgzk/quantstats_4f5cbb4a393f4131a36339534e047e20/setup.py", line 30, in <module>
          with io.open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-l_ropgzk/quantstats_4f5cbb4a393f4131a36339534e047e20/requirements.txt'
      [end of output]
