### ISSUE TITLE
print("在线回测属于付费功能，请联系微信：Yida_Zhang2")

### ISSUE THREAD

**Issue by 2911236097** [UFund-Me/Qbot#56]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [wiki](https://github.com/Charmve/Qbot/wiki) of our library. After that, if you still feel puzzled, please describe the question clearly under this issue.

so?免费开源? funny .

**Comment by milliyang** [comment]
f**king funny, that is not open source;   it's using github and ad

**Comment by eqshen** [comment]
真的被恶心了，费劲巴拉跑起来了，然后给我个广告弹窗。不免费就别在开源版本里面说包含这个功能。👎
