### ISSUE TITLE
你缝合了这么多东西，好歹写个引用出处啊

### ISSUE THREAD

**Issue by MornS0** [UFund-Me/Qbot#62]
## ❓ Questions and Help
我挨个看了一下，你的星星是不是花钱买的？
这不缝合怪吗？

**Comment by MornS0** [comment]
你抄人家的UI，就替换一下东西？？  里面其他东西也都是缝合，UI源https://github.com/ailabx/ailabx.git 
你自己写了多少，你的星星绝对是买的！
什么辣鸡，浪费我一天时间

**Comment by luorock** [comment]
的确没有什么鸟用. 感觉只想收费.

**Comment by Charmve** [comment]
十分抱歉。qbot定位就是一个量化投研工具，引用集成了ailabx quantlab、fund-strategy、inverstool开源工具，也在项目首页详细指出，对作者及其维护人员，表示十分感谢。

**Comment by Charmve** [comment]
> ## ❓ Questions and Help
> 我挨个看了一下，你的星星是不是花钱买的？ 这不缝合怪吗？

这倒着实没有 🈚️

**Comment by Charmve** [comment]
使用体验上确实还有很多很多要做的，毕竟整体框架搭下来也花了好些功夫。的确用了很多大佬的开源工作，十分感谢。一个人的力量是有限的，但我会长期做下去。大家有什么使用上的问题、或者功能需求，都可以反馈，我会积极改进。这是我的微信Yida_Zhang2 ，欢迎加入微信用户交流群。

**Comment by Wendysigh** [comment]
所以目测自己写的只有文件夹里/qbot/
